org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=1G -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.vfs.watch=true
kotlin.code.style=official
kotlin.incremental=true
kotlin.incremental.usePreciseJavaTracking=true
android.useAndroidX=true
android.enableJetifier=false
android.nonFinalResIds=true
android.nonTransitiveRClass=true
android.enableAppCompileTimeRClass=true
android.uniquePackageNames=true
android.packageNamesViolationCheck=true
android.enableR8.fullMode=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=true
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false
android.defaults.buildfeatures.viewbinding=false
android.sdk.defaultTargetSdkToCompileSdkIfUnset=true
android.dependency.useConstraints=true
android.usesSdkInManifest.disallowed=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.newDsl=true
android.builtInKotlin=true